apiVersion: v1
kind: Service
metadata:
  name: repl
spec:
  selector:
    srv: repl
  type: NodePort
  ports:
  - port: 10000
    protocol: TCP
    name: repl
    targetPort: 10000
    nodePort: 31553
