apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  selector:
    srv: webapi
  type: NodePort
  ports:
  - name: repl
    port: 10000
    protocol: TCP
    targetPort: 10000
    nodePort: 31552
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 31200
